In [2]:
import pandas as pd
import numpy as np 
# import matplotlib.pyplot as plt 
# import seaborn as sns
import nfl_data_py as nfl

In [35]:
pd.set_option('display.max_columns', None)
nfl.import_seasonal_data(range(2022,2023))

,player_id,season,season_type,completions,attempts,passing_yards,passing_tds,interceptions,sacks,sack_yards,sack_fumbles,sack_fumbles_lost,passing_air_yards,passing_yards_after_catch,passing_first_downs,passing_epa,passing_2pt_conversions,pacr,dakota,carries,rushing_yards,rushing_tds,rushing_fumbles,rushing_fumbles_lost,rushing_first_downs,rushing_epa,rushing_2pt_conversions,receptions,targets,receiving_yards,receiving_tds,receiving_fumbles,receiving_fumbles_lost,receiving_air_yards,receiving_yards_after_catch,receiving_first_downs,receiving_epa,receiving_2pt_conversions,racr,target_share,air_yards_share,wopr_x,special_teams_tds,fantasy_points,fantasy_points_ppr,games,tgt_sh,ay_sh,yac_sh,wopr_y,ry_sh,rtd_sh,rfd_sh,rtdfd_sh,dom,w8dom,yptmpa,ppr_sh
0,00-0019596,2022,REG,490,733,4694.0,25,9.0,22.0,160.0,3,2,5027.0,2292.0,237.0,61.906270,2,16.329448,1.556584,29,-1.0,1,2.0,2.0,5.0,-20.469321,0,0,1,0.0,0,0.0,0.0,16.0,0.0,0.0,-4.726016,0,0.000000,0.034483,0.061303,0.094636,0.0,271.66,271.66,17,0.001332,0.003100,0.000000,0.004477,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.175012
1,00-0022824,2022,REG,1,1,4.0,0,0.0,0.0,0.0,0,0,0.0,4.0,1.0,2.864477,0,0.000000,0.000000,0,0.0,0,0.0,0.0,0.0,0.000000,0,0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.0,0.16,0.16,1,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,0.000000,0.000000,NaN,NaN,0.000000,0.002352
2,00-0023459,2022,REG,350,542,3695.0,26,12.0,32.0,258.0,4,2,4327.0,1893.0,177.0,-6.309946,2,16.405610,1.502478,34,94.0,1,2.0,2.0,9.0,-7.814974,0,0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.0,239.20,239.20,17,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.166585
3,00-0024243,2022,REG,0,0,0.0,0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.000000,0,0.000000,0.000000,0,0.0,0,0.0,0.0,0.0,0.000000,0,6,7,66.0,2,0.0,0.0,58.0,14.0,5.0,6.967597,1,5.423810,0.224952,0.196983,0.475316,0.0,20.60,26.60,6,0.034826,0.033276,0.020528,0.078860,0.047619,0.222222,0.070423,0.087500,0.134921,0.082540,0.328358,0.051556
4,00-0026143,2022,REG,309,461,3057.0,14,13.0,38.0,287.0,12,3,2772.0,1405.0,156.0,-24.760006,0,13.382329,0.737524,27,70.0,1,3.0,2.0,9.0,-11.035300,0,0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.0,155.28,155.28,12,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.155439
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
614,00-0038128,2022,REG,31,61,276.0,0,3.0,10.0,49.0,1,0,498.0,144.0,11.0,-38.837689,0,3.464383,-0.027944,27,123.0,1,2.0,2.0,8.0,-6.886303,0,0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.0,19.34,19.34,7,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.049304
615,00-0038129,2022,REG,0,0,0.0,0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.000000,0,0.000000,0.000000,0,0.0,0,0.0,0.0,0.0,0.000000,0,42,65,391.0,2,0.0,0.0,384.0,174.0,19.0,4.972101,0,19.296639,1.423885,1.300855,3.046426,0.0,51.10,93.10,14,0.101721,0.090780,0.087569,0.225206,0.097336,0.090909,0.091787,0.091703,0.094123,0.096051,0.611894,0.071070
616,00-0038134,2022,REG,0,0,0.0,0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.000000,0,0.000000,0.000000,228,1050.0,9,0.0,0.0,51.0,-14.810522,0,27,35,165.0,0,0.0,0.0,-75.0,221.0,6.0,-11.958612,0,-30.399037,1.030760,-0.468127,1.218452,0.0,175.50,202.50,15,0.068762,-0.019836,0.134756,0.087275,0.043160,0.000000,0.032609,0.028708,0.021580,0.034528,0.324165,0.147356
617,00-0038147,2022,REG,0,0,0.0,0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.000000,0,0.000000,0.000000,0,0.0,0,0.0,0.0,0.0,0.000000,0,2,2,25.0,0,0.0,0.0,25.0,0.0,2.0,1.791362,0,1.000000,0.076923,0.223214,0.271635,0.0,2.50,4.50,1,0.071429,0.193798,0.000000,0.262182,0.155280,0.000000,0.200000,0.181818,0.077640,0.124224,0.892857,0.069402
618,00-0038149,2022,REG,0,0,0.0,0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.000000,0,0.000000,0.000000,0,0.0,0,0.0,0.0,0.0,0.000000,0,0,1,0.0,0,0.0,0.0,45.0,0.0,0.0,-0.519020,0,0.000000,0.035714,0.134731,0.147883,0.0,0.00,0.00,1,0.033333,0.127119,0.000000,0.151695,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [38]:
games

,game_id,season,game_type,week,gameday,weekday,gametime,away_team,away_score,home_team,home_score,location,result,total,overtime,old_game_id,gsis,nfl_detail_id,pfr,pff,espn,ftn,away_rest,home_rest,away_moneyline,home_moneyline,spread_line,away_spread_odds,home_spread_odds,total_line,under_odds,over_odds,div_game,roof,surface,temp,wind,away_qb_id,home_qb_id,away_qb_name,home_qb_name,away_coach,home_coach,referee,stadium_id,stadium
0,1999_01_MIN_ATL,1999,REG,1,1999-09-12,Sunday,NaN,MIN,17.0,ATL,14.0,Home,-3.0,31.0,0.0,1999091210,598,NaN,199909120atl,NaN,190912001,NaN,7,7,NaN,NaN,-4.0,NaN,NaN,49.0,NaN,NaN,0,dome,astroturf,NaN,NaN,00-0003761,00-0002876,Randall Cunningham,Chris Chandler,Dennis Green,Dan Reeves,Gerry Austin,ATL00,Georgia Dome
1,1999_01_KC_CHI,1999,REG,1,1999-09-12,Sunday,NaN,KC,17.0,CHI,20.0,Home,3.0,37.0,0.0,1999091206,597,NaN,199909120chi,NaN,190912003,NaN,7,7,NaN,NaN,-3.0,NaN,NaN,38.0,NaN,NaN,0,outdoors,grass,80.0,12.0,00-0006300,00-0010560,Elvis Grbac,Shane Matthews,Gunther Cunningham,Dick Jauron,Phil Luckett,CHI98,Soldier Field
2,1999_01_PIT_CLE,1999,REG,1,1999-09-12,Sunday,NaN,PIT,43.0,CLE,0.0,Home,-43.0,43.0,0.0,1999091213,604,NaN,199909120cle,NaN,190912005,NaN,7,7,NaN,NaN,-6.0,NaN,NaN,37.0,NaN,NaN,1,outdoors,grass,78.0,12.0,00-0015700,00-0004230,Kordell Stewart,Ty Detmer,Bill Cowher,Chris Palmer,Bob McElwee,CLE00,Cleveland Browns Stadium
3,1999_01_OAK_GB,1999,REG,1,1999-09-12,Sunday,NaN,OAK,24.0,GB,28.0,Home,4.0,52.0,0.0,1999091208,602,NaN,199909120gnb,NaN,190912009,NaN,7,7,NaN,NaN,9.0,NaN,NaN,43.0,NaN,NaN,0,outdoors,grass,67.0,10.0,00-0005741,00-0005106,Rich Gannon,Brett Favre,Jon Gruden,Ray Rhodes,Tony Corrente,GNB00,Lambeau Field
4,1999_01_BUF_IND,1999,REG,1,1999-09-12,Sunday,NaN,BUF,14.0,IND,31.0,Home,17.0,45.0,0.0,1999091202,591,NaN,199909120clt,NaN,190912011,NaN,7,7,NaN,NaN,-3.0,NaN,NaN,45.5,NaN,NaN,1,dome,astroturf,NaN,NaN,00-0005363,00-0010346,Doug Flutie,Peyton Manning,Wade Phillips,Jim Mora,Ron Blum,IND99,RCA Dome
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7264,2025_19_GB_CHI,2025,WC,19,2026-01-10,Saturday,20:00,GB,NaN,CHI,NaN,Home,NaN,NaN,NaN,2026011001,60165,NaN,202601100chi,NaN,40172981,7007.0,6,6,-125.0,105.0,-1.5,-112.0,-108.0,44.5,-112.0,-108.0,1,outdoors,NaN,NaN,NaN,00-0036264,00-0039918,Jordan Love,Caleb Williams,Matt LaFleur,Ben Johnson,NaN,CHI98,Soldier Field
7265,2025_19_BUF_JAX,2025,WC,19,2026-01-11,Sunday,13:00,BUF,NaN,JAX,NaN,Home,NaN,NaN,NaN,2026011100,60166,NaN,202601110jax,NaN,40172977,7008.0,7,7,-112.0,-108.0,-1.5,102.0,-122.0,51.5,-108.0,-112.0,0,outdoors,NaN,NaN,NaN,00-0034857,00-0036971,Josh Allen,Trevor Lawrence,Sean McDermott,Liam Coen,NaN,JAX00,TIAA Bank Stadium
7266,2025_19_SF_PHI,2025,WC,19,2026-01-11,Sunday,16:30,SF,NaN,PHI,NaN,Home,NaN,NaN,NaN,2026011101,60167,NaN,202601110phi,NaN,40172980,7009.0,8,7,220.0,-270.0,6.0,-112.0,-108.0,44.5,-112.0,-108.0,0,outdoors,NaN,NaN,NaN,00-0037834,00-0036389,Brock Purdy,Jalen Hurts,Kyle Shanahan,Nick Sirianni,NaN,PHI00,Lincoln Financial Field
7267,2025_19_LAC_NE,2025,WC,19,2026-01-11,Sunday,20:00,LAC,NaN,NE,NaN,Home,NaN,NaN,NaN,2026011102,60168,NaN,202601110nwe,NaN,40172978,7010.0,7,7,160.0,-192.0,3.5,-112.0,-108.0,45.5,-105.0,-115.0,0,outdoors,NaN,NaN,NaN,00-0036355,00-0039851,Justin Herbert,Drake Maye,Jim Harbaugh,Mike Vrabel,NaN,BOS00,Gillette Stadium
7268,2025_19_HOU_PIT,2025,WC,19,2026-01-12,Monday,20:00,HOU,NaN,PIT,NaN,Home,NaN,NaN,NaN,2026011200,60169,NaN,202601120pit,NaN,40172976,7011.0,8,8,-155.0,130.0,-3.0,-102.0,-118.0,38.5,-115.0,-105.0,0,outdoors,grass,NaN,NaN,00-0039163,00-0023459,C.J. Stroud,Aaron Rodgers,DeMeco Ryans,Mike Tomlin,NaN,PIT00,Acrisure Stadium

In [ ]:
import datetime as dt

games = nfl.import_schedules(range(1999, dt.datetime.now().year + 1))
games

,game_id,season,game_type,week,gameday,weekday,gametime,away_team,away_score,home_team,home_score,location,result,total,overtime,old_game_id,gsis,nfl_detail_id,pfr,pff,espn,ftn,away_rest,home_rest,away_moneyline,home_moneyline,spread_line,away_spread_odds,home_spread_odds,total_line,under_odds,over_odds,div_game,roof,surface,temp,wind,away_qb_id,home_qb_id,away_qb_name,home_qb_name,away_coach,home_coach,referee,stadium_id,stadium
0,1999_01_MIN_ATL,1999,REG,1,1999-09-12,Sunday,NaN,MIN,17.0,ATL,14.0,Home,-3.0,31.0,0.0,1999091210,598,NaN,199909120atl,NaN,190912001,NaN,7,7,NaN,NaN,-4.0,NaN,NaN,49.0,NaN,NaN,0,dome,astroturf,NaN,NaN,00-0003761,00-0002876,Randall Cunningham,Chris Chandler,Dennis Green,Dan Reeves,Gerry Austin,ATL00,Georgia Dome
1,1999_01_KC_CHI,1999,REG,1,1999-09-12,Sunday,NaN,KC,17.0,CHI,20.0,Home,3.0,37.0,0.0,1999091206,597,NaN,199909120chi,NaN,190912003,NaN,7,7,NaN,NaN,-3.0,NaN,NaN,38.0,NaN,NaN,0,outdoors,grass,80.0,12.0,00-0006300,00-0010560,Elvis Grbac,Shane Matthews,Gunther Cunningham,Dick Jauron,Phil Luckett,CHI98,Soldier Field
2,1999_01_PIT_CLE,1999,REG,1,1999-09-12,Sunday,NaN,PIT,43.0,CLE,0.0,Home,-43.0,43.0,0.0,1999091213,604,NaN,199909120cle,NaN,190912005,NaN,7,7,NaN,NaN,-6.0,NaN,NaN,37.0,NaN,NaN,1,outdoors,grass,78.0,12.0,00-0015700,00-0004230,Kordell Stewart,Ty Detmer,Bill Cowher,Chris Palmer,Bob McElwee,CLE00,Cleveland Browns Stadium
3,1999_01_OAK_GB,1999,REG,1,1999-09-12,Sunday,NaN,OAK,24.0,GB,28.0,Home,4.0,52.0,0.0,1999091208,602,NaN,199909120gnb,NaN,190912009,NaN,7,7,NaN,NaN,9.0,NaN,NaN,43.0,NaN,NaN,0,outdoors,grass,67.0,10.0,00-0005741,00-0005106,Rich Gannon,Brett Favre,Jon Gruden,Ray Rhodes,Tony Corrente,GNB00,Lambeau Field
4,1999_01_BUF_IND,1999,REG,1,1999-09-12,Sunday,NaN,BUF,14.0,IND,31.0,Home,17.0,45.0,0.0,1999091202,591,NaN,199909120clt,NaN,190912011,NaN,7,7,NaN,NaN,-3.0,NaN,NaN,45.5,NaN,NaN,1,dome,astroturf,NaN,NaN,00-0005363,00-0010346,Doug Flutie,Peyton Manning,Wade Phillips,Jim Mora,Ron Blum,IND99,RCA Dome
5,1999_01_SF_JAX,1999,REG,1,1999-09-12,Sunday,NaN,SF,3.0,JAX,41.0,Home,38.0,44.0,0.0,1999091212,603,NaN,199909120jax,NaN,190912030,NaN,7,7,NaN,NaN,5.5,NaN,NaN,49.0,NaN,NaN,0,outdoors,grass,76.0,8.0,00-0018441,00-0002110,Steve Young,Mark Brunell,Steve Mariucci,Tom Coughlin,Bernie Kukar,JAX00,Alltel Stadium
6,1999_01_CAR_NO,1999,REG,1,1999-09-12,Sunday,NaN,CAR,10.0,NO,19.0,Home,9.0,29.0,0.0,1999091203,592,NaN,199909120nor,NaN,190912018,NaN,7,7,NaN,NaN,3.5,NaN,NaN,38.0,NaN,NaN,1,dome,astroturf,NaN,NaN,00-0001218,00-0007530,Steve Beuerlein,Billy Joe Hobert,George Seifert,Mike Ditka,Larry Nemmers,NOR00,Louisiana Superdome
7,1999_01_NE_NYJ,1999,REG,1,1999-09-12,Sunday,NaN,NE,30.0,NYJ,28.0,Home,-2.0,58.0,0.0,1999091207,600,NaN,199909120nyj,NaN,190912020,NaN,7,7,NaN,NaN,7.0,NaN,NaN,44.5,NaN,NaN,1,outdoors,astroturf,73.0,5.0,00-0001361,00-0016193,Drew Bledsoe,Vinny Testaverde,Pete Carroll,Bill Parcells,Bill Carollo,NYC00,Giants Stadium
8,1999_01_ARI_PHI,1999,REG,1,1999-09-12,Sunday,NaN,ARI,25.0,PHI,24.0,Home,-1.0,49.0,0.0,1999091200,588,NaN,199909120phi,NaN,190912021,NaN,7,7,NaN,NaN,-3.0,NaN,NaN,37.0,NaN,NaN,1,outdoors,astroturf,75.0,3.0,00-0013042,00-0012726,Jake Plummer,Doug Pederson,Vince Tobin,Andy Reid,Ron Winter,PHI99,Veterans Stadium
9,1999_01_DET_SEA,1999,REG,1,1999-09-12,Sunday,NaN,DET,28.0,SEA,20.0,Home,-8.0,48.0,0.0,1999091209,596,NaN,199909120sea,NaN,190912026,NaN,7,7,NaN,NaN,9.5,NaN,NaN,42.0,NaN,NaN,0,dome,astroturf,NaN,NaN,00-0000865,00-0009311,Charlie Batch,Jon Kitna,Bobby Ross,Mike Holmgren,Dick Hantak,SEA98,Seattle Kingdome
10,1999_01_BAL_STL,1999,REG,1,1999-09-12,Sunday,NaN,BAL,10.0,STL,27.0,Home,17.0,37.0,0.0,1999091201,589,NaN,199909120ram,NaN,190912014,NaN,7,7,NaN,NaN,0.0,NaN,NaN,39.0,NaN,NaN,0,dome,astroturf,NaN,NaN,00-0011434,00-0017200,Scott Mitchell,Kurt Waner,Brian Billick,Dick Vermeil,Tom White,STL00,TWA Dome
11,1999_01_NYG_TB,1999,REG,1,1999-09-12,Sunday,NaN,NYG,17.0,TB,13.0,Home,-4.0,30.0,0.0,1999091211,601,NaN,199909120tam,NaN,190912027,NaN,7,7,NaN,NaN,5.5,NaN,NaN,37.5,NaN,NaN,0,outdoors,grass,88.0,8.0,00-0006212,00-0004293,Kent Graham,Trent Dilfer,Jim Fassel,Tony Dungy,Ed Hochuli,TAM00,Raymond James Stadium
12,1999_01_CIN_TEN,1999,REG,1,1999-09-12,Sunday,NaN,CIN,35.0,TEN,36.0,Home,1.0,71.0,0.0,1999091204,594,NaN,199909120oti,NaN,190912010,NaN,7,7,NaN,NaN,9.0,NaN,NaN,42.0,NaN,NaN,1,outdoors,grass,84.0,10.0,00-0001335,00-0011024,Jeff Blake,Steve McNair,Bruce Coslet,Jeff Fisher,Mike Carey,NAS00,Adelphia Coliseum
13,1999_01_DAL_WAS,1999,REG,1,1999-09-12,Sunday,NaN,DAL,41.0,WAS,35.0,Home,-6.0,76.0,1.0,1999091205,595,NaN,199909120was,NaN,190912028,NaN,7,7,NaN,NaN,2.5,NaN,NaN,42.0,NaN,NaN,1,outdoors,grass,71.0,0.0,00-0000104,00-0008442,Troy Aikman,Brad Johnson,Chan Gailey,Norv Turner,Walt Coleman,WAS00,Jack Kent Cooke Stadium
14,1999_01_MIA_DEN,1999,REG,1,1999-09-13,Monday,NaN,MIA,38.0,DEN,21.0,Home,-17.0,59.0,0.0,1999091300,605,NaN,199909130den,NaN,190913007,NaN,7,7,NaN,NaN,6.0,NaN,NaN,43.0,NaN,NaN,0,outdoors,grass,60.0,5.0,00-0010379,00-0006423,Dan Marino,Brian Griese,Jimmy Johnson,Mike Shanahan,Johnny Grier,DEN99,Mile High Stadium
15,1999_02_PIT_BAL,1999,REG,2,1999-09-19,Sunday,NaN,PIT,23.0,BAL,20.0,Home,-3.0,43.0,0.0,1999091905,614,NaN,199909190rav,NaN,190919033,NaN,7,7,NaN,NaN,-2.5,NaN,NaN,38.0,NaN,NaN,1,outdoors,grass,74.0,7.0,00-0015700,00-0011434,Kordell Stewart,Scott Mitchell,Bill Cowher,Brian Billick,Gerry Austin,BAL00,PSINet Stadium
16,1999_02_NYJ_BUF,1999,REG,2,1999-09-19,Sunday,NaN,NYJ,3.0,BUF,17.0,Home,14.0,20.0,0.0,1999091913,619,NaN,199909190buf,NaN,190919002,NaN,7,7,NaN,NaN,4.0,NaN,NaN,42.0,NaN,NaN,1,outdoors,astroturf,68.0,5.0,00-0011378,00-0005363,Rick Mirer,Doug Flutie,Bill Parcells,Wade Phillips,Ron Winter,BUF00,Ralph Wilson Stadium
17,1999_02_JAX_CAR,1999,REG,2,1999-09-19,Sunday,NaN,JAX,22.0,CAR,20.0,Home,-2.0,42.0,0.0,1999091903,611,NaN,199909190car,NaN,190919029,NaN,7,7,NaN,NaN,-9.5,NaN,NaN,44.0,NaN,NaN,0,outdoors,grass,74.0,3.0,00-0002110,00-0001218,Mark Brunell,Steve Beuerlein,Tom Coughlin,George Seifert,Bill Carollo,CAR00,Ericsson Stadium
18,1999_02_SEA_CHI,1999,REG,2,1999-09-19,Sunday,NaN,SEA,14.0,CHI,13.0,Home,-1.0,27.0,0.0,1999091907,616,NaN,199909190chi,NaN,190919003,NaN,7,7,NaN,NaN,-3.5,NaN,NaN,39.0,NaN,NaN,0,outdoors,grass,76.0,15.0,00-0005379,00-0010560,Glenn Foley,Shane Matthews,Mike Holmgren,Dick Jauron,Mike Carey,CHI98,Soldier Field
19,1999_02_SD_CIN,1999,REG,2,1999-09-19,Sunday,NaN,SD,34.0,CIN,7.0,Home,-27.0,41.0,0.0,1999091906,615,NaN,199909190cin,NaN,190919004,NaN,14,7,NaN,NaN,1.0,NaN,NaN,40.5,NaN,NaN,0,outdoors,astroturf,79.0,5.0,00-0006808,00-0001335,Jim Harbaugh,Jeff Blake,Mike Riley,Bruce Coslet,Johnny Grier,CIN99,Cinergy Field
20,1999_02_GB_DET,1999,REG,2,1999-09-19,Sunday,NaN,GB,15.0,DET,23.0,Home,8.0,38.0,0.0,1999091901,609,NaN,199909190det,NaN,190919008,NaN,7,7,NaN,NaN,-6.5,NaN,NaN,43.0,NaN,NaN,1,dome,astroturf,NaN,NaN,00-0005106,00-0000865,Brett Favre,Charlie Batch,Ray Rhodes,Bobby Ross,Jeff Triplette,DET99,Pontiac Silverdome
21,1999_02_DEN_KC,1999,REG,2,1999-09-19,Sunday,NaN,DEN,10.0,KC,26.0,Home,16.0,36.0,0.0,1999091912,608,NaN,199909190kan,NaN,190919012,NaN,6,7,NaN,NaN,-3.5,NaN,NaN,40.5,NaN,NaN,1,outdoors,grass,69.0,8.0,00-0006423,00-0006300,Brian Griese,Elvis Grbac,Mike Shanahan,Gunther Cunningham,Tom Corrente,KAN00,Arrowhead Stadium
22,1999_02_ARI_MIA,1999,REG,2,1999-09-19,Sunday,NaN,ARI,16.0,MIA,19.0,Home,3.0,35.0,0.0,1999091900,606,NaN,199909190mia,NaN,190919015,NaN,7,6,NaN,NaN,9.0,NaN,NaN,41.0,NaN,NaN,0,outdoors,grass,82.0,13.0,00-0013042,00-0010379,Jake Plummer,Dan Marino,Vince Tobin,Jimmy Johnson,Bob McElwee,MIA00,Pro Player Stadium
23,1999_02_OAK_MIN,1999,REG,2,1999-09-19,Sunday,NaN,OAK,22.0,MIN,17.0,Home,-5.0,39.0,0.0,1999091904,613,NaN,199909190min,NaN,190919016,NaN,7,7,NaN,NaN,11.0,NaN,NaN,47.5,NaN,NaN,0,dome,astroturf,NaN,NaN,00-0005741,00-0003761,Rich Gannon,Randall Cunningham,Jon Gruden,Dennis Green,Larry Nemmers,MIN00,Hubert H. Humphrey Metrodome
24,1999_02_IND_NE,1999,REG,2,1999-09-19,Sunday,NaN,IND,28.0,NE,31.0,Home,3.0,59.0,0.0,1999091902,610,NaN,199909190nwe,NaN,190919017,NaN,7,7,NaN,NaN,4.5,NaN,NaN,45.0,NaN,NaN,1,outdoors,grass,68.0,10.0,00-0010346,00-0001361,Peyton Manning,Drew Bledsoe,Jim Mora,Pete Carroll,Dick Hantak,BOS99,Foxboro Stadium
25,1999_02_WAS_NYG,1999,REG,2,1999-09-19,Sunday,NaN,WAS,50.0,NYG,21.0,Home,-29.0,71.0,0.0,1999091909,618,NaN,199909190nyg,NaN,190919019,NaN,7,7,NaN,NaN,2.5,NaN,NaN,41.0,NaN,NaN,1,outdoors,astroturf,70.0,3.0,00-0008442,00-0006212,Brad Johnson,Kent Graham,Norv Turner,Jim Fassel,Bernie Kukar,NYC00,Giants Stadium
26,1999_02_TB_PHI,1999,REG,2,1999-09-19,Sunday,NaN,TB,19.0,PHI,5.0,Home,-14.0,24.0,0.0,1999091908,617,NaN,199909190phi,NaN,190919021,NaN,7,7,NaN,NaN,-6.5,NaN,NaN,36.5,NaN,NaN,0,outdoors,astroturf,69.0,3.0,00-0004293,00-0012726,Trent Dilfer,Doug Pederson,Tony Dungy,Andy Reid,Ron Blum,PHI99,Veterans Stadium
27,1999_02_NO_SF,1999,REG,2,1999-09-19,Sunday,NaN,NO,21.0,SF,28.0,Home,7.0,49.0,0.0,1999091910,612,NaN,199909190sfo,NaN,190919025,NaN,7,7,NaN,NaN,11.0,NaN,NaN,42.5,NaN,NaN,1,outdoors,grass,70.0,10.0,00-0007530,00-0018441,Billy Joe Hobert,Steve Young,Mike Ditka,Steve Mariucci,Phil Luckett,SFO00,3Com Park
28,1999_02_CLE_TEN,1999,REG,2,1999-09-19,Sunday,NaN,CLE,9.0,TEN,26.0,Home,17.0,35.0,0.0,1999091911,607,NaN,199909190oti,NaN,190919010,NaN,7,7,NaN,NaN,16.0,NaN,NaN,40.0,NaN,NaN,1,outdoors,grass,86.0,10.0,00-0003535,00-0012261,Tim Couch,Neil O'Donnell,Chris Palmer,Jeff Fisher,Ed Hochuli,NAS00,Adelphia Coliseum
29,1999_02_ATL_DAL,1999,REG,2,1999-09-20,Monday,NaN,ATL,7.0,DAL,24.0,Home,17.0,31.0,0.0,1999092000,620,NaN,199909200dal,NaN,190920006,NaN,8,8,NaN,NaN,6.5,NaN,NaN,42.0,NaN,NaN,0,outdoors,astroturf,86.0,16.0,00-0006299,00-0000104,Tony Graziani,Troy Aikman,Dan Reeves,Chan Gailey,Tom White,DAL99,Texas Stadium
30,1999_03_CLE_BAL,1999,REG,3,1999-09-26,Sunday,NaN,CLE,10.0,BAL,17.0,Home,7.0,27.0,0.0,1999092603,624,NaN,199909260rav,NaN,190926033,NaN,7,7,NaN,NaN,12.0,NaN,NaN,36.5,NaN,NaN,1,outdoors,grass,72.0,8.0,00-0003535,00-0002787,Tim Couch,Stoney Case,Chris Palmer,Brian Billick,Bernie Kukar,BAL00,PSINet Stadium
31,1999_03_PHI_BUF,1999,REG,3,1999-09-26,Sunday,NaN,PHI,0.0,BUF,26.0,Home,26.0,26.0,0.0,1999092606,630,NaN,199909260buf,NaN,190926002,NaN,7,7,NaN,NaN,11.5,NaN,NaN,38.0,NaN,NaN,0,outdoors,astroturf,74.0,5.0,00-0012726,00-0005363,Doug Pederson,Doug Flutie,Andy Reid,Wade Phillips,Jeff Triplette,BUF00,Ralph Wilson Stadium
32,1999_03_CIN_CAR,1999,REG,3,1999-09-26,Sunday,NaN,CIN,3.0,CAR,27.0,Home,24.0,30.0,0.0,1999092602,623,NaN,199909260car,NaN,190926029,NaN,7,7,NaN,NaN,7.0,NaN,NaN,39.5,NaN,NaN,0,outdoors,grass,70.0,6.0,00-0001335,00-0001218,Jeff Blake,Steve Beuerlein,Bruce Coslet,George Seifert,Dick Hantak,CAR00,Ericsson Stadium
33,1999_03_MIN_GB,1999,REG,3,1999-09-26,Sunday,NaN,MIN,20.0,GB,23.0,Home,3.0,43.0,0.0,1999092611,629,NaN,199909260gnb,NaN,190926009,NaN,7,7,NaN,NaN,0.0,NaN,NaN,47.5,NaN,NaN,1,outdoors,grass,82.0,20.0,00-0003761,00-0005106,Randall Cunningham,Brett Favre,Dennis Green,Ray Rhodes,Johnny Grier,GNB00,Lambeau Field

In [29]:
nfl.import_team_desc()

,team_abbr,team_name,team_id,team_nick,team_conf,team_division,team_color,team_color2,team_color3,team_color4,team_logo_wikipedia,team_logo_espn,team_wordmark,team_conference_logo,team_league_logo,team_logo_squared
0,ARI,Arizona Cardinals,3800,Cardinals,NFC,NFC West,#97233F,#000000,#ffb612,#a5acaf,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/ari.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
1,ATL,Atlanta Falcons,200,Falcons,NFC,NFC South,#A71930,#000000,#a5acaf,#a30d2d,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/atl.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
2,BAL,Baltimore Ravens,325,Ravens,AFC,AFC North,#241773,#9E7C0C,#9e7c0c,#c60c30,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/bal.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
3,BUF,Buffalo Bills,610,Bills,AFC,AFC East,#00338D,#C60C30,#0c2e82,#d50a0a,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/buf.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
4,CAR,Carolina Panthers,750,Panthers,NFC,NFC South,#0085CA,#000000,#bfc0bf,#0085ca,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500-dark...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
5,CHI,Chicago Bears,810,Bears,NFC,NFC North,#0B162A,#E64100,#0b162a,#E64100,https://upload.wikimedia.org/wikipedia/commons...,https://a.espncdn.com/i/teamlogos/nfl/500/chi.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
6,CIN,Cincinnati Bengals,920,Bengals,AFC,AFC North,#FB4F14,#000000,#000000,#d32f1e,https://upload.wikimedia.org/wikipedia/commons...,https://a.espncdn.com/i/teamlogos/nfl/500/cin.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
7,CLE,Cleveland Browns,1050,Browns,AFC,AFC North,#FF3C00,#311D00,#a5acaf,#d32f1e,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/cle.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
8,DAL,Dallas Cowboys,1200,Cowboys,NFC,NFC East,#002244,#B0B7BC,#acc0c6,#a5acaf,https://upload.wikimedia.org/wikipedia/commons...,https://a.espncdn.com/i/teamlogos/nfl/500/dal.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
9,DEN,Denver Broncos,1400,Broncos,AFC,AFC West,#002244,#FB4F14,#00234c,#ff5200,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/den.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
10,DET,Detroit Lions,1540,Lions,NFC,NFC North,#0076B6,#B0B7BC,#000000,#004e89,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/det.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
11,GB,Green Bay Packers,1800,Packers,NFC,NFC North,#203731,#FFB612,#1c2d25,#eead1e,https://upload.wikimedia.org/wikipedia/commons...,https://a.espncdn.com/i/teamlogos/nfl/500/gb.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
12,HOU,Houston Texans,2120,Texans,AFC,AFC South,#03202F,#A71930,#00071c,#a30d2d,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/hou.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
13,IND,Indianapolis Colts,2200,Colts,AFC,AFC South,#002C5F,#a5acaf,#013369,#9ba1a2,https://upload.wikimedia.org/wikipedia/commons...,https://a.espncdn.com/i/teamlogos/nfl/500/ind.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
14,JAX,Jacksonville Jaguars,2250,Jaguars,AFC,AFC South,#006778,#000000,#9f792c,#d7a22a,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/jax.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
15,KC,Kansas City Chiefs,2310,Chiefs,AFC,AFC West,#E31837,#FFB612,#000000,#e31837,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/kc.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
16,LA,Los Angeles Rams,2510,Rams,NFC,NFC West,#003594,#FFD100,#001532,#af925d,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/lar.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
17,LAC,Los Angeles Chargers,4400,Chargers,AFC,AFC West,#007BC7,#ffc20e,#ffb612,#001532,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/lac.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
18,LAR,Los Angeles Rams,2510,Rams,NFC,NFC West,#003594,#FFD100,#001532,#af925d,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/lar.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
19,LV,Las Vegas Raiders,2520,Raiders,AFC,AFC West,#000000,#A5ACAF,#a6aeb0,#000000,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/lv.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
20,MIA,Miami Dolphins,2700,Dolphins,AFC,AFC East,#008E97,#F58220,#005778,#008e97,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/mia.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
21,MIN,Minnesota Vikings,3000,Vikings,NFC,NFC North,#4F2683,#FFC62F,#e9bf9b,#000000,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/min.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
22,NE,New England Patriots,3200,Patriots,AFC,AFC East,#002244,#C60C30,#b0b7bc,#001532,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/ne.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
23,NO,New Orleans Saints,3300,Saints,NFC,NFC South,#D3BC8D,#000000,#9f8958,#000000,https://upload.wikimedia.org/wikipedia/commons...,https://a.espncdn.com/i/teamlogos/nfl/500/no.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
24,NYG,New York Giants,3410,Giants,NFC,NFC East,#0B2265,#A71930,#a5acaf,#012352,https://upload.wikimedia.org/wikipedia/commons...,https://a.espncdn.com/i/teamlogos/nfl/500/nyg.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
25,NYJ,New York Jets,3430,Jets,AFC,AFC East,#003F2D,#000000,NaN,NaN,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/nyj.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
26,OAK,Oakland Raiders,2520,Raiders,AFC,AFC West,#000000,#A5ACAF,#a6aeb0,#000000,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/lv.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
27,PHI,Philadelphia Eagles,3700,Eagles,NFC,NFC East,#004C54,#A5ACAF,#acc0c6,#000000,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/phi.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
28,PIT,Pittsburgh Steelers,3900,Steelers,AFC,AFC North,#000000,#FFB612,#c60c30,#00539b,https://upload.wikimedia.org/wikipedia/commons...,https://a.espncdn.com/i/teamlogos/nfl/500/pit.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
29,SD,San Diego Chargers,4400,Chargers,AFC,AFC West,#007BC7,#ffc20e,#ffb612,#001532,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/lac.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
30,SEA,Seattle Seahawks,4600,Seahawks,NFC,NFC West,#002244,#69be28,#a5acaf,#001532,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/sea.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
31,SF,San Francisco 49ers,4500,49ers,NFC,NFC West,#AA0000,#B3995D,#000000,#a5acaf,https://upload.wikimedia.org/wikipedia/commons...,https://a.espncdn.com/i/teamlogos/nfl/500/sf.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
32,STL,St. Louis Rams,2510,Rams,NFC,NFC West,#003594,#FFD100,#001532,#af925d,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/lar.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
33,TB,Tampa Bay Buccaneers,4900,Buccaneers,NFC,NFC South,#A71930,#322F2B,#000000,#ff7900,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/tb.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
34,TEN,Tennessee Titans,2100,Titans,AFC,AFC South,#002244,#4B92DB,#c60c30,#a5acaf,https://github.com/nflverse/nflverse-pbp/raw/m...,https://a.espncdn.com/i/teamlogos/nfl/500/ten.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
35,WAS,Washington Commanders,5110,Commanders,NFC,NFC East,#5A1414,#FFB612,#000000,#5b2b2f,https://upload.wikimedia.org/wikipedia/commons...,https://a.espncdn.com/i/teamlogos/nfl/500/wsh.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...

In [ ]:
nfl.import_

WARNING:root:The win totals data source is currently in flux and may be out of date.

,game_id,market_type,abbr,lines,odds,opening_lines,opening_odds,book,season
0,2006_04_ARI_ATL,money_line,ATL,NaN,-345,NaN,NaN,5Dimes,2006
1,2006_04_ARI_ATL,money_line,ATL,NaN,-345,NaN,NaN,sportbet,2006
2,2006_04_ARI_ATL,money_line,ARI,NaN,285,NaN,NaN,5Dimes,2006
3,2006_04_ARI_ATL,money_line,ARI,NaN,285,NaN,NaN,sportbet,2006
4,2006_04_ARI_ATL,money_line,ATL,NaN,-380,NaN,NaN,bet365,2006
...,...,...,...,...,...,...,...,...,...
478076,2021_18_WAS_NYG,total,over,38.5,-114,39.0,-115.0,BETMANIA,2021
478077,2021_18_WAS_NYG,total,under,38.5,-103,39.0,-102.0,SKYBOOK,2021
478078,2021_18_WAS_NYG,total,over,38.5,-117,39.0,-118.0,SKYBOOK,2021
478079,2021_18_WAS_NYG,total,under,38.5,-111,38.5,-111.0,BetRegal,2021
478080,2021_18_WAS_NYG,total,over,38.5,-111,38.5,-111.0,BetRegal,2021